[PRTL-3184] scrna tsv download
NCI-GDC/portal-ui pull request #2920
Opened 2020-09-16 20:14 UTC by samrichca

## Ticket Number

PRTL-3184

## Environment to be used in testing

- [ ] `prod`
- [ ] `dev-oicr`
- [x] `qa-yellow`

## Description of Changes

download TSVs in scrna-seq

2020-09-16 20:18 UTC, caravinci requested changes

2020-09-16 20:18 UTC, caravinci commented on src/packages/@ncigdc/utils/constants.js
> +  false;
```suggestion
  false;

```

2020-09-16 20:18 UTC, caravinci commented on src/packages/@ncigdc/modern_components/SCRNASeq/toolbar/ToolbarButton.js
> +import React from 'react';
```suggestion
```

2020-09-16 20:18 UTC, caravinci commented on src/packages/@ncigdc/modern_components/SCRNASeq/toolbar/DownloadButton.js
>  import DropDown from '@ncigdc/uikit/Dropdown';
```suggestion
import DropDown from '@ncigdc/uikit/Dropdown';
```

2020-09-16 20:18 UTC, caravinci commented on src/packages/@ncigdc/modern_components/SCRNASeq/AnalysisDownloadsButton/AnalysisDownloadsButton.relay.js
> +import React from 'react';
```suggestion
```

2020-09-16 20:18 UTC, caravinci commented on src/packages/@ncigdc/modern_components/SCRNASeq/AnalysisDownloadsButton/AnalysisDownloadsButton.js
> +import React from 'react';
```suggestion
```

2020-09-16 20:28 UTC, caravinci submitted a review, later dismissed

2020-10-14 20:16 UTC, samrichca commented on src/packages/@ncigdc/modern_components/SCRNASeq/toolbar/DownloadButton.js
> -  downloadAnalysis: [
downloadAnalysis moved to its own component because appearance & functionality diverged

2020-10-14 20:17 UTC, samrichca commented on src/packages/@ncigdc/modern_components/SCRNASeq/toolbar/ToolbarButton.js
> -            ...name === 'downloadAnalysis' ? {} : visualizingButton,
again downloadAnalysis punted to its own file here

2020-10-14 20:23 UTC, caravinci approved these changes

2020-10-14 20:36 UTC, merged